pam_pwquality.c: Use pam_modutil_check_user_in_passwd instead of fget…
libpwquality/libpwquality pull request #53
Opened 2021-04-20 15:32 UTC by Thermi

…pwent_r (not available on musl)

Change is like the patch from here: https://github.com/linux-pam/linux-pam/pull/237

Looked good enough for upstream. :)

2021-04-20 16:28 UTC, t8m commented
Hmm, I suppose proper way would be to add configure check for pam_modutil_check_user_in_passwd and fallback to the existing code if it is not present.
Would you please add that?

2021-04-20 18:17 UTC, Thermi commented
I guarded it in an ifdef for a test that checks if the function exists. That should be enough.

2021-05-21 19:09 UTC, Thermi commented
@t8m Please take a look at it again. :)

2021-05-24 07:18 UTC, t8m requested changes

2021-05-24 07:18 UTC, t8m commented on src/pam_pwquality.c
> -        }
Do not delete this `}`

2021-05-24 12:16 UTC, Thermi commented on src/pam_pwquality.c
> -        }
Ty, fixed.

2021-05-24 13:17 UTC, t8m approved these changes

2021-05-24 13:17 UTC, merged

2021-05-24 13:18 UTC, t8m commented
Merged. Thank you for your contribution.